name: Deploy feature branches to nonproduction bucket.

on:
  push:
    branches:
      - feature*

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-fbf4d3f1086cf6986242366a2-nonprodbucket-1izc91laeias1
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deploy files to bucket
<<<<<<< HEAD
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }} --recursive
=======
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }} --recursive
>>>>>>> 9d9b33ae429a417b38e917e0fc7294383c82609b
